ImBIOS/qwiktober-2022

- src/data/contributor.ts
> test commit 2 contrib

- src/data/contributor.ts
> test commit 1 contrib

- public/websites/rodhisz/rodhisz.html
> add rodhisz folder

- public/websites/mem.html
> First commit

- public/websites/mem.html
> simple-navbar

- public/websites/farrelkoplak/koplak.html
> bismillah bisa

- public/websites/tio/tio.html
- src/data/contributor.ts
> Tio profile

- public/websites/Younes-git/Younes.html
> Ingfo masseh

- public/websites/tio/tio.html
- src/data/contributor.ts
> Tio navbar

- public/websites/Arsyad/Arsyad.html
> Arsyad commit

- src/data/contributor.ts
Nur Ihsan Al Ghifari
X RPL - IDN SOLO
> Tambah nama :>

- public/websites/bedull/bedul.py
> add python print

- src/data/contributors.ts
> add comment to my contributors profile

- src/data/contributors.ts
> add Dzikstarts profile

- src/data/contributors.ts
> add noval's contributors profile

- src/data/contributors.ts
> add comment to @nuril profile

- src/data/contributors.ts
> add atha profile

- src/data/contributors.ts
> add zaki profile

- src/data/contributors.ts
> add dzakwan profile

- public/websites/husain/husain.html
> add husain.html

- README.md
Remove unnecessary text in README.md like deployment and add integrations.
> Tidy up and remove unnecessary text in README

- public/websites/AyushBorage/index.html
Hey,
Pls merge this under hacktoberfest label
ThankYou
> Added my website

- README.md
> feat (readme): add customize contributor card

- README.md
> add CodeQL badge

- public/websites/bedull/bedul.py
> Dul add pyhton code

- public/websites/0_x_0/index.html
> add 0_x_0/index.html

- README.md
> Fix Grammar and Alphabetic Error

- public/websites/Ujjwal/Ujjwal.html
> hacktoberfest

- public/websites/muflikhan/muflikhan.html
> Add paragraph in Muflikhan Blog 

- public/websites/dzakwan/ayo.html
> nambah kuy

- public/websites/Zaki/zaki.html
> file html add

- public/websites/Zaki/style.css
- public/websites/Zaki/zaki.html
> File Css Add

- public/websites/Zaki/style.css
- public/websites/Zaki/zaki.html
- public/websites/Zaki/zaki.js
> File JS Add

- public/websites/syafiq/HelloWorld.js
- public/websites/syafiq/HelloWorld.py
- public/websites/syafiq/helloWorld.go
> add how to make hello world in javascript with arrow function

- public/websites/muflikhan/muflikhan.html
- public/websites/muflikhan/script.js
> Add Paragraph 2 in My Blog

- public/websites/nafgeng/index.html
> add doctype

- public/websites/bananaavv/index.html
- src/data/contributors.ts
> add contributor

- public/websites/bananaavv/index.html
- src/data/contributors.ts
> Bananaavv : Add index

- src/data/contributors.ts
> tambah fadlan contributor

- src/data/contributors.ts
> Apa aja boleh

- src/data/contributors.ts
> apa aja deh
